import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black`}
        style={{ backgroundColor: '#000' }}
      >
        <header className="w-full px-6 py-4 bg-transparent fixed top-0 z-50">
          <nav className="max-w-7xl mx-auto flex items-center justify-between">
            <div className="text-white font-semibold">
              <a href="/" className="mr-4">Home</a>
              <a href="/main" className="underline">Main</a>
            </div>
          </nav>
        </header>

        <div className="pt-16">{children}</div>
      </body>
    </html>
  );
}
